TF_TI2_19269_19262/Models/Temporadas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TF_TI2_19269_19262.Models
{
    /// <summary>
    /// Tabela Temporadas:
    ///     - ID : id da temporada (int)
    ///     - Numero : numeor da temporada (int)
    ///     - Nome : nome da temporada (string)
    ///     - Foto : fotografia/imagem da temporada (string)
    ///     - Trailer : trailler da temporada (string)
    ///     - SeriesFK : chave forasteira para a tabela Series (int)
    ///     - Episodios : lista de Episódios  (ICollection)
    /// </summary>
    public class Temporadas
    {
        public Temporadas()
        {
            Episodios = new HashSet<Episodios>();
        }
        /// <summary>
        /// ID : id da temporada (int)
        /// </summary>
        [Key]
        public int ID { get; set; }

        /// <summary>
        /// Numero : numeor da temporada (int)
        /// </summary>
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        public int Numero { get; set; }

        /// <summary>
        /// Nome : nome da temporada (string)
        /// </summary>
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        [DisplayName("Nome Temporada")]
        public string Nome { get; set; }

        /// <summary>
        /// Foto : fotografia/imagem da temporada (string)
        /// </summary>
        public string Foto { get; set; }

        /// <summary>
        /// Trailer : trailler da temporada (string)
        /// </summary>
        public string Trailer { get; set; }

        /// <summary>
        /// SeriesFK : chave forasteira para a tabela Series (int)
        /// </summary>
        [ForeignKey("Serie")]
        public int SerieFK { get; set; }
        public virtual Series Serie { get; set; }

        /// <summary>
        /// Episodios : lista de Episódios  (ICollection)
        /// </summary>
        public virtual ICollection<Episodios> Episodios { get; set; }
    }
}

TF_TI2_19269_19262/Controllers/SeriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using TF_TI2_19269_19262.Models;

namespace TF_TI2_19269_19262.Controllers
{
    public class SeriesController : Controller
    {
        // cria VAR que representa a BD
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Series
        /// <summary>
        /// faz get de todas as séries e respetivas editoras
        /// </summary>
        /// <returns>devolve a view index com os dados das séries e das respetivas editoras</returns>
        public ActionResult Index()
        {
            // procura a totalidade das series na BD
            var series = db.Series.Include(s => s.Editora);
            return View(series.ToList());
        }

        // GET: Series/Details/5
        /// <summary>
        /// faz get dos dados de 1 série
        /// </summary>
        /// <param name="id">id da série</param>
        /// <returns>dados da série cujo id é o fonecido na view details</returns>
        public ActionResult Details(int? id)
        {

            if (id == null)
            { 
                //alterar as rotas por defeito, de modo a não haver erros de BadRequest ou de NotFound  
                return RedirectToAction("Index");
            }
            Series serie = db.Series.Find(id);
            if (serie == null)
            {
                return RedirectToAction("Index");
            }
            return View(serie);
        }

        // GET: Series/Temporadas/5
        /// <summary>
        /// get dos dados das temporadas associadas a 1 série para que posso ir para a página das temporadas
        /// </summary>
        /// <param name="id"></param>
        /// <returns>view das temporadas com os dados das temporadas associadas a 1 série</returns>
        public ActionResult Temporadas(int? id)
        {
            if (id == null)
            {
                //evitar erros de BadRequest e NotFound
                return RedirectToAction("Index");
            }
            var temporadas = db.Temporadas.Where(t => t.SerieFK == id);
            var varSerie = db.Series;
            if (temporadas == null)
            {
                return RedirectToAction("Index");
            }
            return View(temporadas);
        }
        //------------------------------------------------------------------------------------
        // GET: Series/Create
        /*
         * Apenas os utilizadores do tipo "Administrador" poderão criar, editar ou eliminar series
         */
         /// <summary>
         /// faz get dos dados de 1 série e poe os dados de 1 editora (id e nome ) num viewbag
         /// </summary>
         /// <returns>view create</returns>
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.EditoraFK = new SelectList(db.Editora, "ID", "Nome");
            return View();
        }

        // POST: Series/Create
        /// <summary>
        /// cria 1 registo de 1 série na bd incluindo o ficheiro de imagem.devolve mensagem de erro em caso de erro
        /// </summary>
        /// <param name="serie">série (Nome,genero,Sinopse,Video,AuxClassificacao e EditoraFK</param>
        /// <param name="uploadFoto">ficheiro de imagem</param>
        /// <returns>view create com os dados da série ou em caso de erro volta para o idex</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create([Bind(Include = "Nome,Genero,Sinopse,Video,AuxClassificacao,EditoraFK")] Series serie, HttpPostedFileBase uploadFoto)
        {
            try
            {
                //converter o auxClassificacao para double
                serie.Classificacao = Convert.ToDouble(serie.AuxClassificacao);
                int idNovaSerie = db.Series.Max(s => s.ID) + 1;
                serie.ID = idNovaSerie;

                string nomeFoto = "Serie_" + idNovaSerie + ".jpg";

                string path = "";
                //verificar se foi fornecido ficheiro
                //Há ficheiro?
                if (uploadFoto != null)
                {
                    // o ficheiro foi fornecido
                    // validar se o que foi fornecido é uma imagem
                    // criar o caminho completo até ao sítio onde o ficheiro
                    // será guardado
                    path = Path.Combine(Server.MapPath("~/Imagens/"), nomeFoto);

                    //guardar nome do file na bd
                    serie.Foto = nomeFoto;
                }
                //Não havendo ficheiro (e sendo obrigatório) vamos ter de fornecer uma imagem
                else
                {
                    //avisar que nao foi fornecida qualquer imagem
                    ModelState.AddModelError("", "Não foi fornecida uma imagem...");
                    ViewBag.EditoraFK = new SelectList(db.Editora, "ID", "Nome", serie.EditoraFK);

                    return View(serie);
                }

                //se os atributos introduzidos forem validos entra neste if 
                if (ModelState.IsValid)
                {
                    
                    serie.Nome = serie.Nome.Trim();
                    serie.Genero = serie.Genero.Trim();
                    serie.Sinopse = serie.Sinopse.Trim();

                    // valida se os dados fornecidos estão de acordo 
                    // com as regras definidas na especificação do Modelo
                    //adiciona nova serie ao Modelo
                    db.Series.Add(serie);
                    //guarda os dados na bd
                    db.SaveChanges();
                    //guarda a foto no disco rigido
                    uploadFoto.SaveAs(path);
                    // redireciona o utilizador para a página do INDEX
                    return RedirectToAction("Index");
                }

                ViewBag.EditoraFK = new SelectList(db.Editora, "ID", "Nome", serie.EditoraFK);
                return View(serie);
            }
            catch(Exception)
            {
                ModelState.AddModelError("", string.Format("Ocorreu um erro com a criação dos dados da série,tente novamente. "));
                return View(serie);

            }
            
        }

        // GET: Series/Edit/5
        /// <summary>
        /// faz get dos dados de 1 série
        /// </summary>
        /// <param name="id">id da série</param>
        /// <returns> view edit com os dados da série</returns>
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //alterar as respostas por defeito, de modo a não haver erros de BadRequest ou de NotFound  
                return RedirectToAction("Index");
            }
            Series serie = db.Series.Find(id);
            if (serie == null)
            {
                //alterar as respostas por defeito, de modo a não haver erros de BadRequest ou de NotFound  
                return RedirectToAction("Index");
            }
         
            ViewBag.EditoraFK = new SelectList(db.Editora, "ID", "Nome", serie.ID);
            ViewBag.SerieID = new SelectList(db.Editora, "ID", "Nome", serie.ID);

            return View(serie);
        }

        // POST: Series/Edit/5
        /// <summary>
        /// Edita 1 registo de 1 série na bd incluindo o ficheiro de imagem associado.Devolve mensagem de erro em caso de erro 
        /// </summary>
        /// <param name="serie">série (ID, Nome,Genero,Foto,Sinopse,Video,AuxClassificacao,EditoraFK</param>
        /// <param name="editFoto">ficheiro de imagem</param>
        /// <returns>retorna para o series details</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "ID,Nome,Genero,Foto,Sinopse,Video,AuxClassificacao,EditoraFK")] Series serie, HttpPostedFileBase editFoto)
        {
        //converter o atributo auxiliar para double
          serie.Classificacao=Convert.ToDouble(serie.AuxClassificacao);
            // o ficheiro foi fornecido
            // validar se o que foi fornecido é uma imagem
            // criar o caminho completo até ao sítio onde o ficheiro será guardado
            string novoNome = "";
            string nomeAntigo = "";
            bool haFotoNova = false;

            if (ModelState.IsValid)
            {
                 try
                 {
                    if (editFoto != null)
                    {
                        //o nome antigo representa a foto na base de dados já inserida
                        nomeAntigo = serie.Foto;
                        //o novo nome será guardado na bd se for inserida uma nova foto
                        novoNome = "Serie_" + serie.ID + DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetExtension(editFoto.FileName).ToLower();
                        serie.Foto = novoNome;
                        haFotoNova = true;
                    }
                    serie.Nome = serie.Nome.Trim();
                    serie.Genero = serie.Genero.Trim();
                    serie.Sinopse = serie.Sinopse.Trim();
                    db.Entry(serie).State = EntityState.Modified;
                        db.SaveChanges();
                        if (haFotoNova)
                            {
                                // eliminar a foto antiga da bd e guardar a nova foto na bd
                                System.IO.File.Delete(Path.Combine(Server.MapPath("~/Imagens"), nomeAntigo));
                                editFoto.SaveAs(Path.Combine(Server.MapPath("~/Imagens"), novoNome));
                            }
                   }
                catch (Exception)
                {

TF_TI2_19269_19262/Views/Temporadas/Create.cshtml
@model TF_TI2_19269_19262.Models.Temporadas

@{
    ViewBag.Title = "Create";
}

<h2>Criar</h2>


<form action="/Temporadas/Create" method="post" novalidate="novalidate" enctype="multipart/form-data">
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Temporadas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg" name="uploadFoto" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <input name="SerieFK" value="@ViewBag.SerieFK" class="btn btn-default" type="hidden"  />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
    </form>
    

    <div>
        @Html.ActionLink("Voltar à Lista", "Index", new { id = ViewBag.SerieFK })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

TF_TI2_19269_19262/Views/Temporadas/Delete.cshtml
@model TF_TI2_19269_19262.Models.Temporadas

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>Tem a certeza de que quer eliminar?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="display:flex;flex-direction:row;margin-bottom:50px;">
            <div style="display:flex;flex-direction:column;justify-content:space-between"">
                <div class="info">
                    <dt>
                        @Html.DisplayNameFor(model => model.Numero)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Numero)
                    </dd>
                </div>
                <div class="info">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nome)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Nome)
                    </dd>
                </div>
                <div class="info">
                    <dt>
                        @Html.DisplayNameFor(model => model.Trailer)
                    </dt>

                    <dd>
                        <iframe src="https://www.youtube.com/embed/@Html.DisplayFor(model => model.Trailer)" allowfullscreen></iframe>
                    </dd>
                </div>
            </div>
            <div>
                <div style="margin-bottom:24px;">
                    <dt>
                        @Html.DisplayNameFor(model => model.Foto)
                    </dt>

                    <dd>
                        <img src="~/Imagens/@Html.DisplayFor(item => item.Foto)" />
                    </dd>
                </div>
            </div>
        </div>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à Lista", "Index", new { id = Model.SerieFK })
        </div>
    }
</div>


<style>
    .info dt, dd {
        text-align: justify;
        
    }
</style>

TF_TI2_19269_19262/Views/Temporadas/Details.cshtml
@model TF_TI2_19269_19262.Models.Temporadas

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Temporadas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Serie.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trailer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar à Lista", "Index")
</p>

TF_TI2_19269_19262/Views/Temporadas/Edit.cshtml
@model TF_TI2_19269_19262.Models.Temporadas

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


<form action="/Temporadas/Edit" method="post" novalidate="novalidate" enctype="multipart/form-data">
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Temporadas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Foto)

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg" name="editFoto" />
                <img src="~/Imagens/@Model.Foto" width="150" height="200" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                <iframe src="https://www.youtube.com/embed/@Html.DisplayFor(model => model.Trailer)" allowfullscreen></iframe>
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"  style="display:none">
            @Html.LabelFor(model => model.SerieFK, "SerieFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SerieFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SerieFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

    <div>
        @Html.ActionLink("Voltar à lista de Temporadas", "Index", new { id = Model.SerieFK })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

TF_TI2_19269_19262/Views/Temporadas/Index.cshtml
@model IEnumerable<TF_TI2_19269_19262.Models.Temporadas>

@{
    ViewBag.Title = "Index";
}
<link href="~/CSS/MyCSS/temporadasIndex.css" rel="stylesheet" />

<div class="temporadas_index_wrapper">
    <div class="temporadas_index_action">
        <h2>Lista De Temporadas</h2>
    </div>
    <div class="temporadas_index_content">
        
        @foreach (var item in Model)
        {
            
        <div class="temporadas_index_content_wrapper">
            <div class="temporadas_index_content_img">
                <a href="~/Imagens/@item.Foto" target="_blank">
                    <img src="~/Imagens/@item.Foto" />
                </a>
            </div>
            <div class="temporadas_index_info_wrapper">
                <div class="temporadas_index_info">
                    <div class="temporadas_index_info_text">
                        <p>Série:</p>
                        <p>@Html.DisplayFor(modelItem => item.Serie.Nome)</p>
                    </div>
                    <div class="temporadas_index_info_text">
                        <p>Temporada:</p>
                        <p>@Html.DisplayFor(modelItem => item.Numero)</p>
                    </div>
                </div>

                <div class="temporadas_index_info_trailler">
                    <iframe src="https://www.youtube.com/embed/@Html.DisplayFor(modelItem => item.Trailer)" allowfullscreen width="400" height="300"></iframe>
                </div>

                <div class="temporadas_index_info_links">
                    <div class="episodio_botao">
                        <span>@Html.ActionLink("Episódios", "../Episodios/Index", new { id = item.ID })</span>
                    </div>
                    <div class="resto_dos_botoes">
                        @if (User.IsInRole("Administrador"))
                        {
                            <span>@Html.ActionLink("Editar Temporada", "Edit", new { id = item.ID })</span>
                            <span>@Html.Raw("|")</span>
                            <span>@Html.ActionLink("Eliminar Temporada", "Delete", new { id = item.ID })</span>
                        }
                    </div>
                </div>
            </div>
        </div> 
        }
    </div>
</div>

<div id="opt">
    <img id="options" src="~/Imagens/options.png" alt=""/>
</div>
<div class="sidebar_nav">
    <span>@Html.ActionLink("Voltar à Lista de Séries", "Index", "Series", new { id = ViewBag.SerieFK },null)</span>

    @if (User.IsInRole("Administrador"))
    {
    <span>@Html.ActionLink("Criar Nova Temporada", "Create",new { id= ViewBag.SerieFK})</span>
    }
</div>